#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/medilingo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: dbmasteruser
#    password: strong_password
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    mapper:
      accept-case-insensitive-enums: true

jwt:
  secret:
    key: "${JWT_SECRET:7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==}"

openai:
  api-key: ${OPENAI_API_KEY}

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash

openfda:
  api-key: ${OPENFDA_API_KEY:}
  base-url: https://api.fda.gov

rximage:
  base-url: https://rximage.nlm.nih.gov

dailymed:
  base-url: https://dailymed.nlm.nih.gov

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: ${PORT:8080}